wip

diff --git a/subcommands/default b/subcommands/default
--- a/subcommands/default
+++ b/subcommands/default
@@ -49,22 +49,26 @@ letsencrypt_link () {
   declare desc="symlink let's encrypt certificates so they can be found by dokku"
 
   local app="$1"; verify_app_name "$app"
-  local config_dir="$2"
+  local cert_name="$2"
+  local config_dir="$3"
 
   local app_root="$DOKKU_ROOT/$app"
   local le_root="$app_root/letsencrypt"
+  local cert_root="$le_root/$cert_root"
 
   dokku_log_info1 "Installing let's encrypt certificates"
 
   # link the current config directory to 'current'
-  ln -nsf "$config_dir" "$le_root/certs/current"
+  ln -nsf "$config_dir" "$cert_root/certs/current"
 
   # install the let's encrypt certificate for the app
-  if [[ -z $DOKKU_APP_NAME ]]; then
-    dokku certs:add "$app" "$le_root/certs/current/fullchain.pem" "$le_root/certs/current/key.pem"
-  else
-    dokku certs:add "$le_root/certs/current/fullchain.pem" "$le_root/certs/current/key.pem"
-  fi
+  # if [[ -z $DOKKU_APP_NAME ]]; then
+  #   dokku certs:add "$app" "$cert_root/certs/current/fullchain.pem" "$cert_root/certs/current/key.pem"
+  # else
+  #   dokku certs:add "$cert_root/certs/current/fullchain.pem" "$cert_root/certs/current/key.pem"
+  # fi
+
+
 }
 
 
@@ -72,14 +76,15 @@ letsencrypt_acme () {
   #shellcheck disable=SC2034
   declare desc="perform actual ACME validation procedure"
   local app="$1"
-  local acme_port="$2"
+  local cert_name="$2"
+  local acme_port="$3"
 
   letsencrypt_create_root "$app"
 
-  dokku_log_info1 "Getting letsencrypt certificate for ${app}..."
+  dokku_log_info1 "Getting letsencrypt certificate for ${app}/${cert_name}..."
 
   # read simp_le arguments from appropriate config file into the config array
-  local config_dir="$(letsencrypt_configure_and_get_dir "$app")"
+  local config_dir="$(letsencrypt_configure_and_get_dir "$app" "$cert_name")"
   read -r -a config < "$config_dir/config"
 
   eval "$(config_export global)"
@@ -119,7 +124,7 @@ letsencrypt_acme () {
 
   fi
 
-  letsencrypt_link "$app" "$config_dir"
+  # letsencrypt_link "$app" "$cert_name" "$config_dir"
   nginx_build_config "$app"
 }
 
@@ -137,6 +142,7 @@ letsencrypt_default_cmd() {
   ##
 
   local app="$2"
+  local cert_name="$3"
 
   [[ -z "$app" ]] && echo "Please specify an app to run the command on" && exit 1
 
@@ -150,7 +156,7 @@ letsencrypt_default_cmd() {
   letsencrypt_update
 
   letsencrypt_acmeproxy_on "$app" "$acme_port"
-  letsencrypt_acme "$app" "$acme_port" || true    # remove ACME proxy even if this fails
+  letsencrypt_acme "$app" "$cert_name" "$acme_port" || true    # remove ACME proxy even if this fails
   letsencrypt_acmeproxy_off "$app"
 
   dokku_log_verbose "done"
